baseURL: "https://phire.cz/"
languageCode: "en-us"

title: "Martin Herich"

theme: "signature"

params:
  theme: "solarized"
  subtitle: "Software Engineer"
  description: "I build backend systems. Based in Prague."
  elsewhere:
    - title: "github.com/hericmar"
      url: "https://github.com/hericmar"
    - title: "martin.herich@phire.cz"
      url: "mailto:martin.herich@phire.cz"
    - title: "pgp"
      value: "3715 5E55 9CAF 95D1 A680 CA2B 83A3 9511 C627 D7C8"
      url: "https://keys.openpgp.org/vks/v1/by-fingerprint/37155E559CAF95D1A680CA2B83A39511C627D7C8"
